export const SECOND_MS = 1000
export const MINUTE_MS = 60 * SECOND_MS
export const HOUR_MS = 60 * MINUTE_MS
export const DAY_MS = 24 * HOUR_MS

export const AUTO_PAGE_REFRESH_MS = HOUR_MS
export const DOWNLOAD_URL_REVOKE_DELAY_MS = SECOND_MS
export const DEV_SCENE_REFRESH_MS = 800
export const REALTIME_AGE_TICK_MS = SECOND_MS
export const REALTIME_INITIAL_RECONNECT_DELAY_MS = 2 * SECOND_MS
export const REALTIME_MAX_RECONNECT_DELAY_MS = 10 * SECOND_MS
export const REALTIME_STALE_AFTER_SEC = 30
export const SCADA_REALTIME_GRACE_MS = 7 * SECOND_MS
export const TOAST_AUTO_DISMISS_MS = 4500
export const TOKEN_EXPIRY_LEEWAY_SEC = 30
